config/routes.rb
Mfk::Application.routes.draw do
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"  

  resources :sessions

  namespace :admin do
    resources :users
  end
end
#== Route Map
# Generated on 08 Jun 2013 00:46
#
#          logout GET    /logout(.:format)               sessions#destroy
#        sessions GET    /sessions(.:format)             sessions#index
#                 POST   /sessions(.:format)             sessions#create
#     new_session GET    /sessions/new(.:format)         sessions#new
#    edit_session GET    /sessions/:id/edit(.:format)    sessions#edit
#         session GET    /sessions/:id(.:format)         sessions#show
#                 PUT    /sessions/:id(.:format)         sessions#update
#                 DELETE /sessions/:id(.:format)         sessions#destroy
#     admin_users GET    /admin/users(.:format)          admin/users#index
#                 POST   /admin/users(.:format)          admin/users#create
#  new_admin_user GET    /admin/users/new(.:format)      admin/users#new
# edit_admin_user GET    /admin/users/:id/edit(.:format) admin/users#edit
#      admin_user GET    /admin/users/:id(.:format)      admin/users#show
#                 PUT    /admin/users/:id(.:format)      admin/users#update
#                 DELETE /admin/users/:id(.:format)      admin/users#destroy

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.has_role? "admin"
        can :manage, :all
      # else
        # can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Role < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :username, :password, :password_confirmation

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_USERNAME_REGEX = /\A[A-Za-z][A-Za-z0-9._-]{2,19}\z/
  
  has_and_belongs_to_many :roles  

  has_secure_password

  validates :username, presence: true, format: { with: VALID_USERNAME_REGEX },
                    uniqueness: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } 

  before_save { |user| user.email = email.downcase }

  def has_role?(role) 
    self.roles.include? Role.find_by_name(role)
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < BaseController
    layout 'admin'
  
    check_authorization

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to "/login", flash: { error: exception.message }
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to admin_users_path, :flash => { :success => "The user was successfully created" } 
    else
      render action: "new"
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, :flash => { :success => "The user was successfully deleted" } 
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to admin_users_url, :flash => { :success => "The user was successfully updated"}
    else
      render action: "edit"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/admin/users", :flash => { :success => "Logged in!" }
    else
      flash[:error] = "Invalid email or password"
      render action: "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/admin/users", :flash => { :success => "Logged out!" }
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], :html => { :class => "form-horizontal" } do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, "Эл.адрес", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :email, :placeholder => "Электронный адрес" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :username, "Имя пользователя", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :username, :placeholder => "Имя пользователя" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password, "Пароль", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :password, :placeholder => "Пароль" %>
    </div>
  </div> 
  
  <div class="control-group">
    <%= f.label :password_confirmation, "Подтверждение пароля", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :password_confirmation, :placeholder => "Подтверждение пароля" %>
    </div>
  </div> 
  
  <div class="form-actions">
    <%= link_to "Отменить", admin_users_path, :class => 'btn' %>
    или 
    <%= submit_tag("Сохранить", :class => 'btn btn-primary')  %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h2>Редактирование пользователя</h2>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h2>
  Пользователи
  <div class="pull-right">
    <%= link_to 'Новый пользователь', new_admin_user_path, :class => "btn btn-info" %>
  </div>
</h2>

<table class="table">
<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.email, admin_user_path(user) %></td>
    <td><%= user.username %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/admin/users/new.html.erb
<h2>Создание нового пользователя</h2>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<h2>Данные пользователя</h2>

<p>
  <b>Электронный адрес:</b>
  <%= @user.email %>
</p>

<p>
  <b>Имя пользователя:</b>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@user)  %> |
<%= link_to 'Back', admin_users_path %>

app/views/layouts/admin.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]> <html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]> <html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]> <html class="ie ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="en"><!--<![endif]-->

  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <title>Mfk</title>
  </head> 

  <header>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse collapse">
            <% if current_user -%>
              <p class="navbar-text pull-right">
                <%= link_to "Выйти", logout_url %>
              </p>  
              <p class="navbar-text pull-right">
                Вы вошли как: <%= current_user.username %> 
              </p> 
            <% else %>
              <p class="navbar-text pull-right">
                <%= link_to "Войти", login_url %>
              </p>  
            <% end -%>
          </div>  
        </div>
      </div>  
    </div>  
  </header>

  <body>
    <div class="container">
      <div class="row">
        <div class="span4">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Пользователи</li>    
              <li <%= "class=active" if current_page?(admin_users_url) %>>
                <%= link_to "Управление пользователями", admin_users_url %>
              </li>
            </ul>
          </div>
        </div>
        <div class="span8">
          <% flash.each do |key, value| %>
            <%= content_tag :div, class: "alert alert-#{key}" do -%>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= value %>
            <% end -%>
          <% end %>
          <%= yield  %>
        </div>
      </div>
      <div class="row">
        <%= debug(params) if Rails.env.development? %>
        <%= debug(flash) if Rails.env.development? %>
        <%= debug(session) if Rails.env.development? %>
      </div>
    </div>
  </body>

</html>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]> <html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]> <html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]> <html class="ie ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html lang="en"><!--<![endif]-->

  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <title>Mfk</title>
  </head> 

  <header>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">Вы вошли как</p>  
          </div>  
        </div>
      </div>  
    </div>  
  </header>

  <body>
    <div class="container">
      <div class="row">
        <div class="span8">
          <% flash.each do |key, value| %>
            <%= content_tag :div, class: "alert alert-#{key}" do -%>
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= value %>
            <% end -%>
          <% end %>
          <%= yield  %>
        </div>
      </div>
      <div class="row">
        <%= debug(params) if Rails.env.development? %>
        <%= debug(flash) if Rails.env.development? %>
        <%= debug(session) if Rails.env.development? %>
      </div>
    </div>
  </body>

</html>